name: test5

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test5:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        shell: powershell
        run: ./1.build.ps1 test
