name: test7

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test7:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        shell: pwsh
        run: ./1.build.ps1 test
